using Orchestrator.Core.Agents;
using Orchestrator.Core.Graph;

namespace Orchestrator.Infrastructure.Agents;

/// <summary>Per-node-kind role prompt, output schema, effort and (for code agents) the paths the agent may write.</summary>
internal sealed record AgentSpec(string Role, string Schema, AgentEffort Effort, IReadOnlyList<string> Lane);

internal static class AgentSpecs
{
    public const string BaseSystemPrompt = """
        You are one agent in a governed software-delivery pipeline working on a .NET 10 URL shortener.
        The repository (including CLAUDE.md, which defines architecture, security and code conventions) is provided.
        Follow CLAUDE.md exactly. Stay within the scope of the change request; do not refactor unrelated code.
        Your output is reviewed by automated gates (build, tests, secret scan, change-control policy) and by humans.
        Respond only with JSON matching the required schema.
        """;

    private const string CodeChangeSchema = """
        {"type":"object","additionalProperties":false,"required":["summary","files"],
         "properties":{"summary":{"type":"string"},
          "files":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["path","content"],
            "properties":{"path":{"type":"string"},"content":{"type":"string"}}}}}}
        """;

    private static readonly Dictionary<NodeKind, AgentSpec> Specs = new()
    {
        [NodeKind.Requirements] = new(
            """
            Role: requirements analyst. Normalize the change request into a precise engineering problem.
            List testable acceptance criteria, the assumptions you made, and anything out of scope.
            If the request is ambiguous in a way that changes what gets built, put the decisions a human must make
            in openQuestions (otherwise return an empty list). Never invent answers to open questions.
            """,
            """
            {"type":"object","additionalProperties":false,"required":["problem","acceptanceCriteria","assumptions","openQuestions","outOfScope"],
             "properties":{"problem":{"type":"string"},"acceptanceCriteria":{"type":"array","items":{"type":"string"}},
              "assumptions":{"type":"array","items":{"type":"string"}},"openQuestions":{"type":"array","items":{"type":"string"}},
              "outOfScope":{"type":"array","items":{"type":"string"}}}}
            """,
            AgentEffort.Medium, []),
        [NodeKind.Design] = new(
            """
            Role: software architect. Using the requirements and the repository, design the change: impacted files,
            approach, API/schema changes (exact routes, status codes, type and member names the implementer and the
            test writer must both use), and risks. They work in parallel from your design, so be specific.
            Set requiresMigration=true only if the EF Core model changes; then give a PascalCase migrationName.
            """,
            """
            {"type":"object","additionalProperties":false,"required":["approach","impactedFiles","apiChanges","risks","requiresMigration","migrationName"],
             "properties":{"approach":{"type":"string"},"impactedFiles":{"type":"array","items":{"type":"string"}},
              "apiChanges":{"type":"string"},"risks":{"type":"array","items":{"type":"string"}},
              "requiresMigration":{"type":"boolean"},"migrationName":{"type":"string"}}}
            """,
            AgentEffort.High, []),
        [NodeKind.Implement] = new(
            """
            Role: implementer. Implement the design in production code under src/. Return the COMPLETE new content of
            every file you create or change (not a diff). Do not write tests, docs or EF migrations (migrations are
            generated by tooling after you). Never include secrets.
            """,
            CodeChangeSchema, AgentEffort.High, ["src/UrlShortener."]),
        [NodeKind.Tests] = new(
            """
            Role: test engineer. Write xUnit tests for the acceptance criteria under tests/UrlShortener.Tests/, using
            the names from the design and the existing test helpers (e.g. WebApplicationFactory setup). Return the
            COMPLETE content of every file you create or change. Do not modify production code.
            """,
            CodeChangeSchema, AgentEffort.High, ["tests/UrlShortener.Tests/"]),
        [NodeKind.Docs] = new(
            """
            Role: technical writer. Update user-facing documentation for the change (README.md API section and/or
            CHANGELOG.md, docs/). Return the COMPLETE content of every file you create or change. Keep it concise.
            """,
            CodeChangeSchema, AgentEffort.Low, ["README.md", "CHANGELOG.md", "docs/"]),
        [NodeKind.ReleaseReadiness] = new(
            """
            Role: release manager. From the requirements, design, change diffs and validation report, decide whether
            the change is ready to merge. Check each acceptance criterion is covered, tests ran green, and risks have
            mitigations. ready=false blocks the merge, so use it only for real gaps.
            """,
            """
            {"type":"object","additionalProperties":false,"required":["ready","summary","checklist","risks"],
             "properties":{"ready":{"type":"boolean"},"summary":{"type":"string"},
              "checklist":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["item","status"],
                "properties":{"item":{"type":"string"},"status":{"type":"string","enum":["pass","fail","n/a"]}}}},
              "risks":{"type":"array","items":{"type":"string"}}}}
            """,
            AgentEffort.Medium, []),
    };

    public static bool Supports(NodeKind kind) => Specs.ContainsKey(kind);

    public static AgentSpec For(NodeKind kind) =>
        Specs.TryGetValue(kind, out var spec) ? spec : throw new NotSupportedException($"No LLM agent for node kind {kind}.");
}
